version: '3.1'

services:
  mariadb:
    image: mariadb:10.6.12
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goorm  # 초기화할 데이터베이스 이름
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # 초기화 스크립트를 복사
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: